apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Programming\Code\Node\Architecture\kompose.exe convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: booking
  name: booking
spec:
  ports:
  - name: "4241"
    port: 4241
    targetPort: 4241
  selector:
    io.kompose.service: booking
status:
  loadBalancer: {}
